apiVersion: v1
kind: Pod
metadata:
    name: mongo-pod
    labels: 
        app: microservice-libreria
        name: mongo-pod
spec:
    containers:
    - name: mongo
      image: mongo
      command:
      - /bin/bash
      - -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "alejandropons"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "12345"
      ports:
        - containerPort: 27017
